version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: coursedb.cf6k226muoj8.ap-south-1.rds.amazonaws.com
      DB_USER: admin
      DB_PASS: YourSecurePassword123
      DB_NAME: coursedb
      JWT_SECRET: YourSuperSecretJWTKey

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
